spring:
  data:
    mongodb:
      database: chatdb
      port: 27018
      host: localhost
      username: chatdbuser
      password: PSqPrvulabKbQzA6xTHK0kHvssdvgyEQxMkJoK0107CI7nTPVa

jpa:
  properties:
    hibernate:
      ogm:
        datastore:
          create_database=true:
server:
  port: 3000
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic